cache: bundler

language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.9.0
  - jruby-head
  - ruby-head

sudo: false

bundler_args: --without development --retry=3 --jobs=3

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

script: bundle exec rspec

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
